--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-pattern
  region: eu-west-1
  version: "1.25"
managedNodeGroups:
- name: general
  privateNetworking: true
  instanceType: t3.medium
  desiredCapacity: 2
  iam:
    attachPolicyARNs:
      - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
      - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
      - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
      - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
      - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
    withAddonPolicies:
      albIngress: true
iam:
  withOIDC: true

addons:
- name: aws-ebs-csi-driver
  version: v1.23.0-eksbuild.1
  tags:
    team: eks
  attachPolicyARNs:
  - arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy
